<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetLib)</TargetFramework>
    <RootNamespace>SportFieldBooking.KiemThu</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SportFieldBooking.Core\SportFieldBooking.Core.csproj" />
    <ProjectReference Include="..\..\src\SportFieldBooking.Data\SportFieldBooking.Data.csproj" />
    <ProjectReference Include="..\..\src\SportFieldBooking.Business\SportFieldBooking.Business.csproj" />
  </ItemGroup>

</Project>
