<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetLib)</TargetFramework>
    <RootNamespace>SportFieldBooking.Core</RootNamespace>
    <AssemblyName>SportFieldBooking.Core</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
