<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetLib)</TargetFramework>
    <RootNamespace>SportFieldBooking.Business</RootNamespace>
    <AssemblyName>SportFieldBooking.Business</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SportFieldBooking.Core\SportFieldBooking.Core.csproj" />
    <ProjectReference Include="..\SportFieldBooking.Data\SportFieldBooking.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="SportFieldBooking.Core.Entities" />
    <Using Include="SportFieldBooking.Core.Common" />
  </ItemGroup>
</Project>
